class ExampleGenerator<Rails::Generators::Base
    argument :name
    desc "This generator creates a file and print out your name"
    def create_controller_file
        create_file "app/controllers/example_controller.rb","class ExampleController<ApplicationController\nend\n#this file is generated by generators:rails generate example Raj"
    end
    def print_name
        puts "hello #{name},Your generator Worked!!"
    end
end