class ExampleGenerator<Rails::Generators::Base
    argument :name
    desc "This generator creates a file and print out your name ,also added routes."
    def print_name
        puts "hello #{name},Your generator Worked!!"
    end
    def create_controller_file
        create_file "app/controllers/example_controller.rb","class ExampleController<ApplicationController\ndef index\nend\nend\n#this file is generated by generators:rails generate example Raj"
        create_file "app/views/example/index.html.erb","hello #{name}."
    end
    def add_resource_route
        route_config = "resources :examples\n root \"example#index\"" 
        route route_config
      end
end